[package]
name = "seesea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
inkwell = { version = "0.2.0", features = ["llvm16-0"] }